#Configuración IOP
#Sun Apr 05 19:50:17 CST 2026
api.cid=bMsmOTeAw/fj3Fng/ieoQWBmyeNvqWAX
api.endpoint.device=/device/getDeviceList
api.endpoint.location=/device/getLocationList
api.endpoint.login=/user/login
api.pass=Rb1t3ch2026
api.url=https\://device.vernal.ltd/tagapi
api.user=Rbitech2026
iop.filetag=tag_event.txt
iop.nombre=TSIGO_RBI
rabbitmq.exchange=change
rabbitmq.pass=test
rabbitmq.port=5672
rabbitmq.provider=T-SIGO-01
rabbitmq.topic=iop.vid.custom
rabbitmq.uri=192.168.1.65
rabbitmq.user=prueba
rabbitmq.vhost=/
redis.frecuencia=60
redis.pass=
redis.port=6379
redis.uri=192.168.1.65
